language: rust
dist: xenial

rust:
    - "1.36.0"
    - "1.37.0"
    - "1.38.0"
    - "1.39.0"
    - "1.40.0"
    - "1.41.1"
    - "1.42.0"
    - "1.43.1"
    - "stable"
    - "beta"
    - "nightly"

jobs:
    allow_failure:
        - rust: "nightly"
    include:
        - name: Run cargo audit
          rust: stable
          env: TASK=audit
    fast_finish: true

install:
    - cargo build --verbose
    - if [ "$TASK" = "audit" ]; then cargo install cargo-audit; fi

script:
    - if [ "$TASK" = "audit" ]; then
          cargo audit;
      else
          cargo test --verbose;
      fi
