language: rust
dist: xenial

rust:
    - "1.32.0"
    - "1.33.0"
    - "1.34.2"
    - "1.35.0"
    - "1.36.0"
    - "1.37.0"
    - "stable"
    - "beta"
    - "nightly"

matrix:
    allow_failure:
        - rust: "nightly"
    include:
        - name: Run cargo audit
          rust: stable
          env: TASK=audit
    fast_finish: true

install:
    - cargo build --verbose
    - if [ "$TASK" = "audit" ]; then cargo install cargo-audit; fi

script:
    - if [ "$TASK" = "audit" ]; then
          cargo audit;
      else
          cargo test --verbose;
      fi
