language: rust

rust:
    - "1.42.0"
    - "1.43.1"
    - "1.44.1"
    - "1.45.2"
    - "1.46.0"
    - "1.47.0"
    - "1.48.0"
    - "1.49.0"
    - "1.50.0"
    - "1.51.0"
    - "1.52.1"
    - "stable"
    - "beta"
    - "nightly"

jobs:
    allow_failures:
        - rust: "nightly"
    include:
        - name: Run cargo audit
          rust: stable
          env: TASK=audit
    fast_finish: true

install:
    - cargo build --verbose
    - if [ "$TASK" = "audit" ]; then cargo install cargo-audit; fi

script:
    - if [ "$TASK" = "audit" ]; then
          cargo audit;
      else
          cargo test --verbose;
      fi
