language: rust
dist: xenial

rust:
    - "1.32.0"
    - "1.33.0"
    - "1.34.2"
    - "stable"
    - "beta"
    - "nightly"

matrix:
    allow_failure:
        - rust: "nightly"
    fast_finish: true
