[package]
name = "tacd"
version = "0.12.0"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
description = "TLS-ALPN Challenge Daemon"
readme = "../README.md"
repository = "https://github.com/breard-r/acmed"
license = "MIT OR Apache-2.0"
keywords = ["acme", "tls", "alpn", "X.509"]
categories = ["cryptography"]
include = ["src/**/*", "Cargo.toml", "LICENSE-*.txt"]
publish = false

[features]
default = ["openssl_dyn"]
openssl_dyn = ["acme_common/openssl_dyn"]

[dependencies]
acme_common = { path = "../acme_common" }
clap = "2.32"
log = "0.4"
openssl = "0.10"
