[global]
accounts_directory = "/etc/acmed/accounts"
certificates_directory = "/etc/acmed/certs"

[[endpoint]]
name = "letsencrypt v2 prod"
url = "https://acme-v02.api.letsencrypt.org/directory"
tos_agreed = false

[[endpoint]]
name = "letsencrypt v2 staging"
url = "https://acme-staging-v02.api.letsencrypt.org/directory"
tos_agreed = false

[[hook]]
name = "http-echo-create"
type = ["challenge-http-01"]
cmd = "echo"
args = ["{{proof}}"]
stdout = "/srv/http/{{domain}}/.well-known/acme-challenge/{{file_name}}"

[[hook]]
name = "http-echo-clean"
type = ["challenge-http-01-clean"]
cmd = "rm"
args = [
    "-f",
    "/srv/http/{{domain}}/.well-known/acme-challenge/{{file_name}}"
]

[[group]]
name = "http-echo"
hooks = ["http-echo-create", "http-echo-clean"]

[[hook]]
name = "email-report"
type = ["post-operation"]
cmd = "sendmail"
args = [
    "-f", "noreply@example.org",
    "john.doe@example.org"
]
stdin = """Subject: Certificate renewal alert for {{domains.[0]}}

The following certificate is being renewed.
domains: {{#each domains}}{{#if @index}}, {{/if}}{{this}}{{/each}}
algorithm: {{algorithm}}
status: {{status}}"""

[[account]]
name = "test_account"
email = "certs@example.org"

[[certificate]]
account = "test_account"
endpoint = "letsencrypt v2 staging"
domains = [
    { dns = "example.org", challenge = "http-01"},
    { dns = "sub-1.example.org", challenge = "http-01" },
    { dns = "sub-2.example.org", challenge = "http-01" }
]
algorithm = "ecdsa_p384"
kp_reuse = false
hooks = ["http-echo", "email-report"]
