[global]
accounts_directory = "/etc/acmed/accounts"
certificates_directory = "/etc/acmed/certs"

[[endpoint]]
name = "letsencrypt v2 prod"
url = "https://acme-v02.api.letsencrypt.org/directory"
tos_agreed = false

[[endpoint]]
name = "letsencrypt v2 staging"
url = "https://acme-staging-v02.api.letsencrypt.org/directory"
tos_agreed = false

[[hook]]
name = "http-echo"
cmd = "echo"
args = ["{{proof}}"]
stdout = "/srv/http/{{current_domain}}/.well-known/acme-challenge/{{file_name}}"

[[hook]]
name = "email-report"
cmd = "sendmail"
args = [
    "-f", "noreply@example.org",
    "john.doe@example.org"
]
stdin = """Subject: Certificate renewal alert for {{domains.[0]}}

The following certificate is being renewed.
domains: {{#each domains}}{{#if @index}}, {{/if}}{{this}}{{/each}}
algorithm: {{algorithm}}
challenge: {{challenge}}
status: {{status}}"""

[[account]]
name = "test_account"
email = "certs@example.org"

[[certificate]]
account = "test_account"
endpoint = "letsencrypt v2 staging"
domains = [
    "example.org",
    "sub-1.example.org",
    "sub-2.example.org"
]
algorithm = "ecdsa_p384"
kp_reuse = false
challenge = "http-01"
challenge_hooks = ["http-echo"]
post_operation_hooks = ["email-report"]
