[package]
name = "acmed"
version = "0.12.0"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
description = "ACME (RFC 8555) client daemon"
readme = "../README.md"
repository = "https://github.com/breard-r/acmed"
license = "MIT OR Apache-2.0"
keywords = ["acme", "tls", "X.509"]
categories = ["cryptography"]
build = "build.rs"
include = ["src/**/*", "Cargo.toml", "LICENSE-*.txt"]
publish = false

[features]
default = ["openssl_dyn"]
openssl_dyn = ["acme_common/openssl_dyn", "attohttpc/tls"]

[dependencies]
acme_common = { path = "../acme_common" }
attohttpc = { version = "0.15", default-features = false, features = ["charsets", "json"] }
bincode = "1.3"
clap = "2.32"
glob = "0.3"
handlebars = "3.0"
log = "0.4"
nom = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"

[target.'cfg(unix)'.dependencies]
nix = "0.18"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
