[package]
name = "acmed"
version = "0.2.1"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
description = "ACME (RFC 8555) client daemon"
keywords = ["acme", "tls", "X.509"]
repository = "https://github.com/breard-r/acmed"
readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml", "LICENSE-*.txt"]

[dependencies]
acme-lib = "0.5"
clap = "2.32"
daemonize = "0.3"
env_logger = "0.6"
handlebars = "2.0.0-beta.1"
log = "0.4"
openssl = "0.10"
pem = "0.5"
serde = { version = "1.0", features = ["derive"] }
syslog = "4.0"
time = "0.1"
toml = "0.5"
x509-parser = "0.4"

[target.'cfg(unix)'.dependencies]
nix = "0.13"
