[package]
name = "acmed"
version = "0.2.1"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
description = "ACME (RFC 8555) client daemon"
keywords = ["acme", "tls", "X.509"]
repository = "https://github.com/breard-r/acmed"
readme = "../README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml", "LICENSE-*.txt"]
build = "build.rs"

[dependencies]
base64 = "0.10"
clap = "2.32"
daemonize = "0.4"
env_logger = "0.6"
handlebars = "2.0.0-beta.1"
http_req = "0.4"
log = "0.4"
openssl = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syslog = "4.0"
time = "0.1"
toml = "0.5"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[target.'cfg(unix)'.dependencies]
nix = "0.13"
