[package]
name = "acmed"
version = "0.8.0"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
description = "ACME (RFC 8555) client daemon"
keywords = ["acme", "tls", "X.509"]
repository = "https://github.com/breard-r/acmed"
readme = "../README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml", "LICENSE-*.txt"]
build = "build.rs"
publish = false

[dependencies]
acme_common = { path = "../acme_common" }
attohttpc = { version = "0.15", features = ["charsets", "json"] }
clap = "2.32"
handlebars = "3.0"
log = "0.4"
nom = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"

[target.'cfg(unix)'.dependencies]
nix = "0.17"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
