[package]
name = "acme_common"
version = "0.6.0"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
repository = "https://github.com/breard-r/libreauth"
readme = "../README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml", "Licence_*.txt"]

[lib]
name = "acme_common"

[features]
default = ["openssl"]
standalone = ["ring"]

[dependencies]
base64 = "0.10"
daemonize = "0.4"
env_logger = "0.6"
handlebars = "2.0.0-beta.2"
http_req = "0.5"
log = "0.4"
openssl = { version = "0.10", optional = true }
ring = { version = "0.14", optional = true }
serde_json = "1.0"
syslog = "4.0"
time = "0.1"
toml = "0.5"

[target.'cfg(unix)'.dependencies]
nix = "0.14"
