[package]
name = "acme_common"
version = "0.6.0"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
repository = "https://github.com/breard-r/libreauth"
readme = "../README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml", "Licence_*.txt"]
publish = false

[lib]
name = "acme_common"

[dependencies]
base64 = "0.10"
daemonize = "0.4"
env_logger = "0.7"
handlebars = "2.0"
http_req = "0.5"
log = "0.4"
openssl = "0.10"
serde_json = "1.0"
syslog = "4.0"
time = "0.1"
toml = "0.5"
x509-parser = "0.6"

[target.'cfg(unix)'.dependencies]
nix = "0.15"
