[package]
name = "acme_common"
version = "0.12.0"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
edition = "2018"
repository = "https://github.com/breard-r/libreauth"
readme = "../README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml", "Licence_*.txt"]
publish = false

[lib]
name = "acme_common"

[features]
default = []
openssl_dyn = ["openssl", "openssl-sys"]

[dependencies]
attohttpc = { version = "0.15", default-features = false }
base64 = "0.12"
daemonize = "0.4"
env_logger = "0.7"
glob = "0.3"
handlebars = "3.0"
libc = "0.2"
log = "0.4"
native-tls = "0.2"
openssl = { version = "0.10", optional = true }
openssl-sys = { version = "0.9", optional = true }
punycode = "0.4"
serde_json = "1.0"
syslog = "5.0"
toml = "0.5"

[target.'cfg(unix)'.dependencies]
nix = "0.18"
